version: '3.7'

services:

  db1:
    container_name: db1
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - db_1:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=db123456
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pdb123456"]
      interval: 10s
      timeout: 5s
      retries: 3

  db2:
    container_name: db2
    image: mysql
    ports:
      - 3308:3306
    volumes:
      - db_2:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=db123456
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pdb123456"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    container_name: backend
    build: 
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 4444:4444
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: sh -c "node src/seed.js && npm start" 
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 80:3001
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_1:
  db_2:
